# check cosine similarity between two vectors saved in npy files and euclidean distance
import numpy as np
def compareVectors(file1, file2):
    vec1 = np.load(file1)
    vec2 = np.load(file2)
    
    # Ensure vectors are 1D
    vec1 = vec1.flatten()
    vec2 = vec2.flatten()
    
    # Cosine similarity
    cos_sim = np.dot(vec1, vec2) / (np.linalg.norm(vec1) * np.linalg.norm(vec2))
    
    # Euclidean distance
    euclidean_dist = np.linalg.norm(vec1 - vec2)
    
    print(f"Cosine Similarity: {cos_sim}")
    print(f"Euclidean Distance: {euclidean_dist}")
if __name__ == "__main__":
    # Paths to the files you want to compare
    # File 1: The ground truth from your bulk embedding script
    file1 = "./image_3889.npy" 
    
    # File 2: The vector generated by ClipEmbedder
    file2 = "./image_3889_test2.npy" 

    compareVectors(file1, file2)