package cat.dog.utility;

import java.io.BufferedReader;
import java.io.File;
import java.io.InputStreamReader;

/**
 * Utility tool to compare two .npy vector files.
 * Calculates Euclidean Distance and Cosine Similarity to verify consistency.
 */
public class VectorComparator {

    private static final String VENV_DIR_NAME = ".venv";
    private static final String PYTHON_EXEC;

    static {
        boolean isWindows = System.getProperty("os.name").toLowerCase().contains("win");
        if (isWindows) {
            PYTHON_EXEC = VENV_DIR_NAME + File.separator + "Scripts" + File.separator + "python.exe";
        } else {
            PYTHON_EXEC = VENV_DIR_NAME + File.separator + "bin" + File.separator + "python3";
        }
    }

    public static void main(String[] args) {
        // Paths to the files you want to compare
        // File 1: The ground truth from your bulk embedding script
        String file1 = "./image_3889.npy"; 
        
        // File 2: The vector generated by ClipEmbedder
        String file2 = "./image_3889_vector.npy"; 

        compareVectors(file1, file2);
    }

    public static void compareVectors(String path1, String path2) {
        File f1 = new File(path1);
        File f2 = new File(path2);

        if (!f1.exists() || !f2.exists()) {
            System.err.println("Error: One or both files do not exist.");
            System.err.println("File 1 exists? " + f1.exists() + " (" + path1 + ")");
            System.err.println("File 2 exists? " + f2.exists() + " (" + path2 + ")");
            return;
        }

        String absPath1 = f1.getAbsolutePath().replace("\\", "\\\\");
        String absPath2 = f2.getAbsolutePath().replace("\\", "\\\\");

        String pythonScript = 
            "import numpy as np\n" +
            "try:\n" +
            "    v1 = np.load('" + absPath1 + "').flatten()\n" +
            "    v2 = np.load('" + absPath2 + "').flatten()\n" +
            "    \n" +
            "    # 1. Calculate Norms (Lengths)\n" +
            "    norm1 = np.linalg.norm(v1)\n" +
            "    norm2 = np.linalg.norm(v2)\n" +
            "    \n" +
            "    # 2. Calculate Euclidean Distance\n" +
            "    euclidean_dist = np.linalg.norm(v1 - v2)\n" +
            "    \n" +
            "    # 3. Calculate Cosine Similarity\n" +
            "    # Dot product / (Mag A * Mag B)\n" +
            "    dot_product = np.dot(v1, v2)\n" +
            "    cosine_sim = dot_product / (norm1 * norm2)\n" +
            "    \n" +
            "    print(f'Norm (File 1): {norm1}')\n" +
            "    print(f'Norm (File 2): {norm2}')\n" +
            "    print(f'Euclidean Distance: {euclidean_dist}')\n" +
            "    print(f'Cosine Similarity:  {cosine_sim}')\n" +
            "    \n" +
            "    if euclidean_dist < 1e-5:\n" +
            "        print('VERDICT: VECTORS ARE IDENTICAL')\n" +
            "    elif cosine_sim > 0.999:\n" +
            "        print('VERDICT: HIGHLY SIMILAR (Same direction, different magnitude?)')\n" +
            "    else:\n" +
            "        print('VERDICT: DIFFERENT VECTORS')\n" +
            "        \n" +
            "except Exception as e:\n" +
            "    print(f'ERROR: {e}')";

        try {
            ProcessBuilder pb = new ProcessBuilder(PYTHON_EXEC, "-c", pythonScript);
            pb.redirectErrorStream(true);
            Process process = pb.start();

            BufferedReader reader = new BufferedReader(new InputStreamReader(process.getInputStream()));
            String line;
            while ((line = reader.readLine()) != null) {
                System.out.println(line);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}